{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dokops.fullname" . }}-backend
  namespace: {{ include "dokops.namespace" . }}
  labels:
    {{- include "dokops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "dokops.selectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.containerPort }}
    protocol: TCP
{{- end }}
