{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dokops.fullname" . }}-frontend
  namespace: {{ include "dokops.namespace" . }}
  labels:
    {{- include "dokops.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "dokops.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.containerPort }}
    protocol: TCP
{{- end }}
